#' @title Date Extract
#' @author Robert Lee \email{rlee@battelleecology.org}\cr
#'
#' @description Extract data between specified start and end times.
#'
#' @param data A data frame generated by the Noble package.
#' @param bgn.date The beginning time to extract data for, as YYYY-MM-DD hh:mm:ss
#' @param end.date The end time to extract data for, as YYYY-MM-DD hh:mm:ss
#'
#' @return A data frame with data collected between \code{bgn.time} and \code{end.time}.
#'
#' @keywords data, subset, date,
#'
#' @examples
#' \dontrun{
#' data=Noble::pull.data(site = "CPER", dp.id = "DP1.00001.001", bgn.month = "2017-08",
#' end.month = "2017-08", time.agr = 30, save.dir = tempdir())
#' ## Extract data from Aug 8th, UTC.
#' aug8=date.extract(data=data, bgn.date = "2017-08-08", end.date = "2017-08-09")
#' }
#'
#' @export date.extract
#'
# # changelog and author contributions / copyrights
#   Robert Lee (2017-10-26)
#     original creation
#
##############################################################################################

## Funciton start
date.extract=function(data, bgn.date, end.date){
    data.out=data[which(as.POSIXct(data[,1], tz = "UTC")>bgn.date & as.POSIXct(data[,1], tz="UTC")<end.date),]
    return(data.out)
}
